#!/usr/bin/env python

# Written by Chris Pressey of Cat's Eye Technologies.
# This work is in the public domain; see UNLICENSE for more information.

import os
import sys

print os.path.realpath(sys.argv[1])
